### ISSUE TITLE
Tyler isn't using the issue tracking

### ISSUE THREAD

**Issue by alexpiet** [alexpiet/dynamic_ephys#1]
- [x] Tyler isn't using the issue tracking
- [x] Tyler is working on a branch without a pull request open
- [x] Tyler isn't using the projects.
